
# from datetime import datetime, timedelta
import sqlite3
from  chpp import CHPPhelp
import xml.etree.ElementTree as ET
# from colorama import init, Fore, Back, Style

conn = sqlite3.connect('bigdata.sqlite')
cur = conn.cursor()

xmldoc = '''
<HattrickData>
  <FileName>matchlineup.xml</FileName>
  <Version>2.0</Version>
  <UserID>10150426</UserID>
  <FetchedDate>2017-10-18 15:50:31</FetchedDate>
  <MatchID>615085410</MatchID>
  <IsYouth>False</IsYouth>
  <MatchType>3</MatchType>
  <MatchDate>2017-10-11 12:00:00</MatchDate>
  <HomeTeam>
    <HomeTeamID>796332</HomeTeamID>
    <HomeTeamName>Los Peques Campeones</HomeTeamName>
  </HomeTeam>
  <AwayTeam>
    <AwayTeamID>120994</AwayTeamID>
    <AwayTeamName>V@der SC</AwayTeamName>
  </AwayTeam>
  <Arena>
    <ArenaID>799770</ArenaID>
    <ArenaName>PEQUELANDIA HAUSE</ArenaName>
  </Arena>
  <Team>
    <TeamID>120994</TeamID>
    <TeamName>V@der SC</TeamName>
    <ExperienceLevel>9</ExperienceLevel>
    <StyleOfPlay>-2</StyleOfPlay>
    <StartingLineup>
      <Player>
        <PlayerID>389005502</PlayerID>
        <RoleID>100</RoleID>
        <FirstName>Damián</FirstName>
        <LastName>Sala</LastName>
        <NickName></NickName>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>379629767</PlayerID>
        <RoleID>101</RoleID>
        <FirstName>Csaba</FirstName>
        <LastName>Mező</LastName>
        <NickName></NickName>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>373882347</PlayerID>
        <RoleID>103</RoleID>
        <FirstName>Ibiur</FirstName>
        <LastName>Altxakoa</LastName>
        <NickName></NickName>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>384131341</PlayerID>
        <RoleID>105</RoleID>
        <FirstName>Mario</FirstName>
        <LastName>Omarini</LastName>
        <NickName></NickName>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>373182450</PlayerID>
        <RoleID>106</RoleID>
        <FirstName>Morgan</FirstName>
        <LastName>Thomas</LastName>
        <NickName></NickName>
        <Behaviour>3</Behaviour>
      </Player>
      <Player>
        <PlayerID>388939943</PlayerID>
        <RoleID>107</RoleID>
        <FirstName>Gianfranco</FirstName>
        <LastName>Rezza</LastName>
        <NickName></NickName>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>381679648</PlayerID>
        <RoleID>108</RoleID>
        <FirstName>Jorge Walter</FirstName>
        <LastName>Whitaker</LastName>
        <NickName></NickName>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>386416781</PlayerID>
        <RoleID>109</RoleID>
        <FirstName>Emilio</FirstName>
        <LastName>Mochelato</LastName>
        <NickName></NickName>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>380939148</PlayerID>
        <RoleID>110</RoleID>
        <FirstName>Iyad</FirstName>
        <LastName>Chaabo</LastName>
        <NickName></NickName>
        <Behaviour>3</Behaviour>
      </Player>
      <Player>
        <PlayerID>391880826</PlayerID>
        <RoleID>111</RoleID>
        <FirstName>Rasheed</FirstName>
        <LastName>Da'na</LastName>
        <NickName></NickName>
        <Behaviour>2</Behaviour>
      </Player>
      <Player>
        <PlayerID>391954865</PlayerID>
        <RoleID>113</RoleID>
        <FirstName>Saúl</FirstName>
        <LastName>Piña</LastName>
        <NickName></NickName>
        <Behaviour>2</Behaviour>
      </Player>
      <Player>
        <PlayerID>384131341</PlayerID>
        <RoleID>17</RoleID>
        <FirstName>Mario</FirstName>
        <LastName>Omarini</LastName>
        <NickName></NickName>
      </Player>
      <Player>
        <PlayerID>391954865</PlayerID>
        <RoleID>18</RoleID>
        <FirstName>Saúl</FirstName>
        <LastName>Piña</LastName>
        <NickName></NickName>
      </Player>
    </StartingLineup>
    <Substitutions>
      <Substitution>
        <TeamID>120994</TeamID>
        <SubjectPlayerID>381679648</SubjectPlayerID>
        <ObjectPlayerID>391014759</ObjectPlayerID>
        <OrderType>1</OrderType>
        <NewPositionId>108</NewPositionId>
        <NewPositionBehaviour>1</NewPositionBehaviour>
        <MatchMinute>75</MatchMinute>
        <MatchPart>2</MatchPart>
      </Substitution>
      <Substitution>
        <TeamID>120994</TeamID>
        <SubjectPlayerID>373882347</SubjectPlayerID>
        <ObjectPlayerID>373882347</ObjectPlayerID>
        <OrderType>1</OrderType>
        <NewPositionId>103</NewPositionId>
        <NewPositionBehaviour>1</NewPositionBehaviour>
        <MatchMinute>75</MatchMinute>
        <MatchPart>2</MatchPart>
      </Substitution>
      <Substitution>
        <TeamID>120994</TeamID>
        <SubjectPlayerID>373182450</SubjectPlayerID>
        <ObjectPlayerID>389206860</ObjectPlayerID>
        <OrderType>1</OrderType>
        <NewPositionId>106</NewPositionId>
        <NewPositionBehaviour>3</NewPositionBehaviour>
        <MatchMinute>78</MatchMinute>
        <MatchPart>2</MatchPart>
      </Substitution>
    </Substitutions>
    <Lineup>
      <Player>
        <PlayerID>389005502</PlayerID>
        <RoleID>100</RoleID>
        <FirstName>Damián</FirstName>
        <LastName>Sala</LastName>
        <NickName></NickName>
        <RatingStars>9</RatingStars>
        <RatingStarsEndOfMatch>8.5</RatingStarsEndOfMatch>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>379629767</PlayerID>
        <RoleID>101</RoleID>
        <FirstName>Csaba</FirstName>
        <LastName>Mező</LastName>
        <NickName></NickName>
        <RatingStars>9</RatingStars>
        <RatingStarsEndOfMatch>8</RatingStarsEndOfMatch>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>373882347</PlayerID>
        <RoleID>103</RoleID>
        <FirstName>Ibiur</FirstName>
        <LastName>Altxakoa</LastName>
        <NickName></NickName>
        <RatingStars>7.5</RatingStars>
        <RatingStarsEndOfMatch>6</RatingStarsEndOfMatch>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>384131341</PlayerID>
        <RoleID>105</RoleID>
        <FirstName>Mario</FirstName>
        <LastName>Omarini</LastName>
        <NickName></NickName>
        <RatingStars>9.5</RatingStars>
        <RatingStarsEndOfMatch>8.5</RatingStarsEndOfMatch>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>389206860</PlayerID>
        <RoleID>106</RoleID>
        <FirstName>Cezary</FirstName>
        <LastName>Pauch</LastName>
        <NickName></NickName>
        <RatingStars>7</RatingStars>
        <RatingStarsEndOfMatch>7</RatingStarsEndOfMatch>
        <Behaviour>3</Behaviour>
      </Player>
      <Player>
        <PlayerID>388939943</PlayerID>
        <RoleID>107</RoleID>
        <FirstName>Gianfranco</FirstName>
        <LastName>Rezza</LastName>
        <NickName></NickName>
        <RatingStars>9.5</RatingStars>
        <RatingStarsEndOfMatch>9</RatingStarsEndOfMatch>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>391014759</PlayerID>
        <RoleID>108</RoleID>
        <FirstName>Adam</FirstName>
        <LastName>Moss</LastName>
        <NickName></NickName>
        <RatingStars>8</RatingStars>
        <RatingStarsEndOfMatch>8</RatingStarsEndOfMatch>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>386416781</PlayerID>
        <RoleID>109</RoleID>
        <FirstName>Emilio</FirstName>
        <LastName>Mochelato</LastName>
        <NickName></NickName>
        <RatingStars>9</RatingStars>
        <RatingStarsEndOfMatch>8</RatingStarsEndOfMatch>
        <Behaviour>1</Behaviour>
      </Player>
      <Player>
        <PlayerID>380939148</PlayerID>
        <RoleID>110</RoleID>
        <FirstName>Iyad</FirstName>
        <LastName>Chaabo</LastName>
        <NickName></NickName>
        <RatingStars>8.5</RatingStars>
        <RatingStarsEndOfMatch>7</RatingStarsEndOfMatch>
        <Behaviour>3</Behaviour>
      </Player>
      <Player>
        <PlayerID>391880826</PlayerID>
        <RoleID>111</RoleID>
        <FirstName>Rasheed</FirstName>
        <LastName>Da'na</LastName>
        <NickName></NickName>
        <RatingStars>11.5</RatingStars>
        <RatingStarsEndOfMatch>11</RatingStarsEndOfMatch>
        <Behaviour>2</Behaviour>
      </Player>
      <Player>
        <PlayerID>391954865</PlayerID>
        <RoleID>113</RoleID>
        <FirstName>Saúl</FirstName>
        <LastName>Piña</LastName>
        <NickName></NickName>
        <RatingStars>11.5</RatingStars>
        <RatingStarsEndOfMatch>10.5</RatingStarsEndOfMatch>
        <Behaviour>2</Behaviour>
      </Player>
      <Player>
        <PlayerID>388962726</PlayerID>
        <RoleID>115</RoleID>
        <FirstName>Andrea</FirstName>
        <LastName>Califano</LastName>
        <NickName></NickName>
        <RatingStars>0</RatingStars>
        <RatingStarsEndOfMatch>0</RatingStarsEndOfMatch>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>383374593</PlayerID>
        <RoleID>119</RoleID>
        <FirstName>Mateusz</FirstName>
        <LastName>Brzostowski</LastName>
        <NickName></NickName>
        <RatingStars>0</RatingStars>
        <RatingStarsEndOfMatch>0</RatingStarsEndOfMatch>
        <Behaviour>0</Behaviour>
      </Player>
      <Player>
        <PlayerID>384131341</PlayerID>
        <RoleID>17</RoleID>
        <FirstName>Mario</FirstName>
        <LastName>Omarini</LastName>
        <NickName></NickName>
      </Player>
      <Player>
        <PlayerID>391954865</PlayerID>
        <RoleID>18</RoleID>
        <FirstName>Saúl</FirstName>
        <LastName>Piña</LastName>
        <NickName></NickName>
      </Player>
      <Player>
        <PlayerID>381679648</PlayerID>
        <RoleID>19</RoleID>
        <FirstName>Jorge Walter</FirstName>
        <LastName>Whitaker</LastName>
        <NickName></NickName>
        <RatingStars>9</RatingStars>
        <RatingStarsEndOfMatch>8.5</RatingStarsEndOfMatch>
      </Player>
      <Player>
        <PlayerID>373182450</PlayerID>
        <RoleID>20</RoleID>
        <FirstName>Morgan</FirstName>
        <LastName>Thomas</LastName>
        <NickName></NickName>
        <RatingStars>7</RatingStars>
        <RatingStarsEndOfMatch>6.5</RatingStarsEndOfMatch>
      </Player>
    </Lineup>
  </Team>
</HattrickData>'''

root = ET.fromstring(xmldoc)

hteamid = root.find('HomeTeam/HomeTeamID').text
print(hteamid)
ateamid = root.find('AwayTeam/AwayTeamID').text
print(ateamid)
teamidlineaup = root.find('Team/TeamID').text
print(teamidlineaup)
if hteamid == teamidlineaup: teamrole = 1
if ateamid == teamidlineaup: teamrole = 2
print(teamrole)
for player in root.findall('Team/StartingLineup/Player'):
    idplayer = player.find('PlayerID').text
    print(idplayer)
    idrole = player.find('RoleID').text
    print(idrole)
    try:
        cur.execute('''INSERT INTO alineacion (MatchID, RoleTeam, RoleID, PlayerID)
                    VALUES (?, ?, ?, ?)''', (idpartido, teamrole, idrole, idplayer))
        conn.commit()
    except:
        continue

cur.close()
